//---------------------------------------------------------------------------------
// GBA PCXView sample code for devkitARM - http://www.devkit.tk
// Suitable for a splash screen for a game
//---------------------------------------------------------------------------------
#include "gba_video.h"
#include "gba_systemcalls.h"
#include "gba_input.h"
#include "gba_interrupt.h"
#include "pcx.h"
#include "fade.h"
#include "mbv2.h"

#include <stdlib.h>

//---------------------------------------------------------------------------------
// header for binary data generated by bin2o macro in makefile
//---------------------------------------------------------------------------------
#include "netbsd0_pcx.h"
#include "netbsd1_pcx.h"
#include "netbsd2_pcx.h"
#include "netbsd3_pcx.h"
#include "netbsd4_pcx.h"
#include "netbsd5_pcx.h"
#include "netbsd6_pcx.h"
#include "netbsd7_pcx.h"

//---------------------------------------------------------------------------------
// storage space for palette data
//---------------------------------------------------------------------------------
u16 PaletteBuffer[256];

unsigned int frame;

//---------------------------------------------------------------------------------
void VblankInterrupt()
//---------------------------------------------------------------------------------
{
	frame += 1;
	scanKeys();
}

//---------------------------------------------------------------------------------
// Program entry point
//---------------------------------------------------------------------------------
int main(void)
//---------------------------------------------------------------------------------
{
    int prev = 0;
    int cur = 0;
    uint16_t keys_pressed = 0;
    uint16_t keys_old = 0;
    uint16_t keys_current;
	// Set up the interrupt handlers
	irqInit();

	irqSet( IRQ_VBLANK, VblankInterrupt);

	// Enable Vblank Interrupt to allow VblankIntrWait
	irqEnable(IRQ_VBLANK);

	// Allow Interrupts
	REG_IME = 1;

	SetMode( MODE_4 | BG2_ON );		// screen mode & background to display

    const u8 *IMGS[8] = {
        netbsd0_pcx,
        netbsd1_pcx,
        netbsd2_pcx,
        netbsd3_pcx,
        netbsd4_pcx,
        netbsd5_pcx,
        netbsd6_pcx,
        netbsd7_pcx,
    };

	DecodePCX(netbsd0_pcx, (u16*)VRAM , PaletteBuffer);

	FadeToPalette( PaletteBuffer, 1);

	while (1)
	{
        scanKeys();
        keys_pressed = keysDown();
        keys_current = keysHeld(); 
        keys_pressed = keys_current & ~keys_old; 
        keys_old = keys_current;

        if (keys_pressed & KEY_A) {
            cur = (cur + 1) > 7 ? 0 : cur + 1;
        } else if (keys_pressed & KEY_B) {
            cur = (cur - 1) < 0 ? 7 : cur - 1;
        }

        if (cur != prev) {
            prev = cur;
            DecodePCX(IMGS[cur], (u16*)VRAM, PaletteBuffer);
	        FadeToPalette(PaletteBuffer, 0);
        }

		VBlankIntrWait();
	}
}
